Repository woowa-techcamp-2021/store-6, pull requests merged in 2021-08, with the labels that each got.

#3 Feature/#1 FE 구조 잡기
  .github/workflows/blank.yml
  client/.babelrc
  client/.eslintrc.js
  client/.prettierrc
  client/package.json
  client/src/App.tsx
  client/src/Components/Title.tsx
  client/src/index.html
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.config.js
  client/yarn.lock
Labels: setup, mid priority

#4 Feature/#2 BE 구조 잡기
  server/.env.dev
  server/.eslintignore
  server/.eslintrc.json
  server/.prettierignore
  server/.prettierrc
  server/ormconfig.ts
  server/package.json
  server/src/api/index.ts
  server/src/api/middlewares/error.ts
  server/src/api/routes/version/index.ts
  server/src/api/routes/version/version.controller.ts
  server/src/app.ts
  server/src/bin/www.ts
  server/src/config/index.ts
  server/src/constants/error.ts
  server/src/entity/user.ts
  server/src/loaders/connect.ts
  server/src/loaders/dependencyInjector.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/service/auth.ts
  server/src/utils/errorResponse.ts
  server/tsconfig.json
  server/yarn.lock
Labels: setup, high priority

#8 Feature/#6 DB Schema 설계
  server/ormconfig.ts
  server/package.json
  server/src/entity/cart.ts
  server/src/entity/category.ts
  server/src/entity/like.ts
  server/src/entity/login.ts
  server/src/entity/option.ts
  server/src/entity/optionItem.ts
  server/src/entity/product.ts
  server/src/entity/productImage.ts
  server/src/entity/review.ts
  server/src/entity/shipping.ts
  server/src/entity/user.ts
  server/src/entity/view.ts
  server/src/loaders/entityInjector.ts
  server/src/loaders/index.ts
  server/tsconfig.json
  server/yarn.lock
Labels: high priority, db

#12 [#11]chore: RouterContext.location에 들어가는 불필요한 속성들 제거
  client/src/Components/Hello.tsx
  client/src/core/Router.tsx
Labels: bug

#14 Feature/#10 FE 테스팅 셋업
  .github/workflows/client-jest.yml
  .github/workflows/client-lint.yml
  client/.eslintrc.js
  client/jest.config.js
  client/package.json
  client/src/App.spec.tsx
  client/src/Components/Hello.spec.tsx
  client/src/core/Router.tsx
  client/src/setUpTests.ts
  client/tsconfig.json
  client/yarn.lock
Labels: setup, high priority

#22 Feature/#13 [FE] 상품 컴포넌트 추가
  client/src/Components/ProductItem.tsx
Labels: high priority, feat

#19 Feature/#13 [BE] 인증 API 구현
  server/.env.dev
  server/.eslintrc.json
  server/package.json
  server/src/api/index.ts
  server/src/api/middlewares/error.ts
  server/src/api/routes/auth/authController.ts
  server/src/api/routes/auth/index.ts
  server/src/api/routes/version/index.ts
  server/src/api/routes/version/versionController.ts
  server/src/app.ts
  server/src/config/index.ts
  server/src/constants/error.ts
  server/src/declare/authHelper.ts
  server/src/declare/index.ts
  server/src/entity/cart.ts
  server/src/entity/category.ts
  server/src/entity/like.ts
  server/src/entity/login.ts
  server/src/entity/option.ts
  server/src/entity/optionItem.ts
  server/src/entity/product.ts
  server/src/entity/productImage.ts
  server/src/entity/review.ts
  server/src/entity/shipping.ts
  server/src/entity/user.ts
  server/src/entity/view.ts
  server/src/helper/auth.ts
  server/src/helper/hash.ts
  server/src/helper/jwt.ts
  server/src/loaders/connect.ts
  server/src/loaders/entityInjector.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/loaders/modelInjector.ts
  server/src/model/login.ts
  server/src/model/model.ts
  server/src/model/user.ts
  server/src/service/auth.ts
  server/tsconfig.json
  server/yarn.lock
Labels: high priority, feat

#27 [#26]fix: 토큰 발행 조건 추가
  server/src/service/auth.ts
Labels: bug

#21 Setup/#20 [BE] 테스트코드 셋업
  server/.eslintignore
  server/.prettierignore
  server/jest.config.ts
  server/package.json
  server/src/app.ts
  server/src/bin/www.ts
  server/tests/api/version.test.ts
  server/yarn.lock
Labels: setup, high priority

#30 Feature/#29 [BE] 마이페이지 사용자 관련 API 구현
  server/package.json
  server/src/api/index.ts
  server/src/api/middlewares/attachCurrentUser.ts
  server/src/api/middlewares/error.ts
  server/src/api/middlewares/index.ts
  server/src/api/middlewares/isAuth.ts
  server/src/api/middlewares/isJwtToken.ts
  server/src/api/routes/users/index.ts
  server/src/api/routes/users/usersController.ts
  server/src/constants/error.ts
  server/src/declare/express.ts
  server/src/declare/index.ts
  server/src/loaders/connect.ts
  server/src/loaders/index.ts
  server/src/loaders/modelInjector.ts
  server/src/model/login.ts
  server/src/model/model.ts
  server/src/model/user.ts
  server/src/repository/login.ts
  server/src/repository/user.ts
  server/src/service/auth.ts
  server/src/service/users.ts
  server/yarn.lock
Labels: high priority, feat

#33 Feature/#23 [BE] 상품 리스트 API 구현
  server/.eslintrc.json
  server/src/api/index.ts
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/constants/error.ts
  server/src/entity/category.ts
  server/src/entity/product.ts
  server/src/entity/review.ts
  server/src/repository/product.ts
  server/src/service/product.ts
Labels: high priority, feat

#34 Feature/#24 [FE] 공통 API 및 Types 작성
  .gitignore
  client/.babelrc
  client/.env.dev
  client/package.json
  client/src/lib/api/auth.ts
  client/src/lib/api/cart.ts
  client/src/lib/api/categories.ts
  client/src/lib/api/client.ts
  client/src/lib/api/likes.ts
  client/src/lib/api/products.ts
  client/src/lib/api/request.ts
  client/src/lib/api/reviews.ts
  client/src/lib/api/shipping.ts
  client/src/lib/api/types/auth.ts
  client/src/lib/api/types/cart.ts
  client/src/lib/api/types/categories.ts
  client/src/lib/api/types/common.ts
  client/src/lib/api/types/error.ts
  client/src/lib/api/types/index.ts
  client/src/lib/api/types/likes.ts
  client/src/lib/api/types/products.ts
  client/src/lib/api/types/reviews.ts
  client/src/lib/api/types/shippings.ts
  client/src/lib/api/types/users.ts
  client/src/lib/api/users.ts
  client/src/lib/constants/.gitkeep
  client/src/lib/hooks/.gitkeep
  client/webpack.config.js
  client/yarn.lock
Labels: high priority, feat

#36 Feature [#35] BE 이미지 업로드 미들웨어 생성
  server/.env.dev
  server/package.json
  server/src/api/middlewares/error.ts
  server/src/api/middlewares/index.ts
  server/src/api/middlewares/upload.ts
  server/src/api/routes/users/index.ts
  server/src/api/routes/users/usersController.ts
  server/src/config/index.ts
  server/src/constants/error.ts
  server/src/loaders/express.ts
  server/yarn.lock
Labels: high priority, feat

#40 Feature/#25
  .github/workflows/deploy.yml
  appspec.yml
  scripts/after-deploy.sh
  scripts/before-deploy.sh
Labels: setup, high priority

#44 Feature/#31 [FE] 마이페이지 기능 완성
  client/.eslintrc.js
  client/src/App.tsx
  client/src/Pages/MyPage/__snapshots__/index.spec.tsx.snap
  client/src/Pages/MyPage/index.spec.tsx
  client/src/Pages/MyPage/index.style.ts
  client/src/Pages/MyPage/index.tsx
  client/src/components/Divider/index.tsx
  client/src/components/EmailInput/__snapshots__/index.spec.tsx.snap
  client/src/components/EmailInput/index.spec.tsx
  client/src/components/EmailInput/index.style.ts
  client/src/components/EmailInput/index.tsx
  client/src/components/Input/index.tsx
  client/src/components/PhoneInput/__snapshots__/index.spec.tsx.snap
  client/src/components/PhoneInput/index.spec.tsx
  client/src/components/PhoneInput/index.style.ts
  client/src/components/PhoneInput/index.tsx
  client/src/components/UserInfoInput/__snapshots__/index.spec.tsx.snap
  client/src/components/UserInfoInput/index.spec.tsx
  client/src/components/UserInfoInput/index.style.ts
  client/src/components/UserInfoInput/index.tsx
  client/src/lib/api/types/users.ts
  client/src/lib/api/users.ts
  client/src/styles/app.css
  client/src/utils/validation.tsx
Labels: high priority, feat

#47 Feature/#46 [BE] 회원가입 API 구현
  server/src/api/routes/users/index.ts
  server/src/api/routes/users/usersController.ts
  server/src/constants/error.ts
  server/src/repository/user.ts
  server/src/service/users.ts
Labels: high priority, feat

#49 [hotfix]fix: Pages -> pages
  client/src/pages/MyPage/__snapshots__/index.spec.tsx.snap
  client/src/pages/MyPage/index.spec.tsx
  client/src/pages/MyPage/index.style.ts
  client/src/pages/MyPage/index.tsx
Labels: bug

#54 Feature/#50 [BE] 회원가입 API 유효성 검사 추가
  server/src/api/middlewares/error.ts
  server/src/api/middlewares/upload.ts
  server/src/api/routes/users/index.ts
  server/src/api/routes/users/usersController.ts
  server/src/constants/error.ts
  server/src/helper/validation.ts
  server/src/repository/login.ts
  server/src/repository/user.ts
  server/src/service/auth.ts
  server/src/service/users.ts
Labels: high priority, feat

#55 Feature/#48, 53 [FE] 상품 목록 페이지에서 사용할 레이아웃 설정 및 상태 관리 로직 추가
  client/src/App.tsx
  client/src/assets/index.tsx
  client/src/components/CategoryFilter/index.tsx
  client/src/components/OrderFilter/index.tsx
  client/src/lib/api/types/products.ts
  client/src/pages/ProductList/__snapshots__/index.spec.tsx.snap
  client/src/pages/ProductList/index.spec.tsx
  client/src/pages/ProductList/index.style.tsx
  client/src/pages/ProductList/index.tsx
  client/src/stores/productModule.ts
  client/src/styles/app.css
Labels: setup, high priority, feat

#61 Fix#43 로그아웃 API 함수 호출 시 Header의 토큰 삭제
  client/src/lib/api/auth.ts
Labels: bug, high priority

#59 Feature/#58 [FE] 상태 관리 로직 useReducer로 리팩토링
  client/src/components/CategoryFilter/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/stores/productListModule.ts
  client/src/stores/productModule.ts
Labels: setup, refactor, high priority

#66 Fix#63 API 요청 함수에서 에러가 return타입에 포함되서 타입추론이 안되는 문제
  client/src/lib/api/client.ts
  client/src/lib/api/request.ts
  client/src/lib/api/types/error.ts
Labels: bug, high priority

#68 Refactor#67 컴포넌트 폴더 구조 변경
  client/src/App.tsx
  client/src/components/ProductItem.tsx
  client/src/components/base/Copyright/__snapshots__/index.spec.tsx.snap
  client/src/components/base/Copyright/index.spec.tsx
  client/src/components/base/Copyright/index.tsx
  client/src/components/base/Navigation/index.style.ts
  client/src/components/base/Navigation/index.tsx
  client/src/components/common/Button/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Button/index.spec.tsx
  client/src/components/common/Button/index.tsx
  client/src/components/common/Checkbox/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Checkbox/index.spec.tsx
  client/src/components/common/Checkbox/index.style.ts
  client/src/components/common/Checkbox/index.tsx
  client/src/components/common/Divider/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Divider/index.spec.tsx
  client/src/components/common/Divider/index.tsx
  client/src/components/common/Icon/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Icon/index.spec.tsx
  client/src/components/common/Icon/index.style.ts
  client/src/components/common/Icon/index.tsx
  client/src/components/common/Input/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Input/index.spec.tsx
  client/src/components/common/Input/index.tsx
  client/src/components/common/Space/index.tsx
  client/src/components/login/InputHelp/__snapshots__/index.spec.tsx.snap
  client/src/components/login/InputHelp/index.spec.tsx
  client/src/components/login/InputHelp/index.tsx
  client/src/components/modal/AlertModal/index.style.ts
  client/src/components/modal/AlertModal/index.tsx
  client/src/components/modal/ConfirmModal/index.style.ts
  client/src/components/modal/ConfirmModal/index.tsx
  client/src/components/my/EmailInput/__snapshots__/index.spec.tsx.snap
  client/src/components/my/EmailInput/index.spec.tsx
  client/src/components/my/EmailInput/index.style.ts
  client/src/components/my/EmailInput/index.tsx
  client/src/components/my/PhoneInput/__snapshots__/index.spec.tsx.snap
  client/src/components/my/PhoneInput/index.spec.tsx
  client/src/components/my/PhoneInput/index.style.ts
  client/src/components/my/PhoneInput/index.tsx
  client/src/components/my/UserInfoInput/__snapshots__/index.spec.tsx.snap
  client/src/components/my/UserInfoInput/index.spec.tsx
  client/src/components/my/UserInfoInput/index.style.ts
  client/src/components/my/UserInfoInput/index.tsx
  client/src/components/product/ProductItem/index.style.ts
  client/src/components/product/ProductItem/index.tsx
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/OrderFilter/index.tsx
  client/src/pages/Login/index.style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
  client/src/pages/SignUp/index.style.ts
  client/src/pages/SignUp/index.tsx
  client/src/styles/app.css
Labels: refactor, mid priority

#70 Feature/#65 [FE] 검색 컴포넌트
  client/src/assets/index.tsx
  client/src/components/ProductItem/ProductItem.tsx
  client/src/components/my/UserInfoInput/__snapshots__/index.spec.tsx.snap
  client/src/components/my/UserInfoInput/index.style.ts
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/RecentlySearchTermBox/index.style.tsx
  client/src/components/productList/RecentlySearchTermBox/index.tsx
  client/src/components/productList/SearchBox/index.style.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/productList/SearchTerm/index.style.tsx
  client/src/components/productList/SearchTerm/index.tsx
  client/src/pages/MyPage/__snapshots__/index.spec.tsx.snap
  client/src/pages/MyPage/index.style.ts
  client/src/pages/ProductList/__snapshots__/index.spec.tsx.snap
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
  client/src/stores/productListModule.ts
  client/src/utils/localStorage.tsx
Labels: high priority, feat

#71 Feature/#58 카테고리 컴포넌트
  client/src/assets/index.tsx
  client/src/components/product/ProductItem/__snapshots__/index.spec.tsx.snap
  client/src/components/product/ProductItem/index.spec.tsx
  client/src/components/product/ProductItem/index.style.ts
  client/src/components/productList/CategoryFilter/index.style.ts
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/CategoryItem/index.style.ts
  client/src/components/productList/CategoryItem/index.tsx
  client/src/pages/ProductList/__snapshots__/index.spec.tsx.snap
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
  client/src/stores/productListModule.ts
  client/src/styles/app.css
Labels: high priority, feat

#74 Refactor#56 : 상품 리스트 가져오기 API 수정
  server/src/repository/product.ts
Labels: refactor, high priority

#78 Feature/#77 카테고리 식별 컴포넌트 개발
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/CategoryIdentifier/index.style.ts
  client/src/components/productList/CategoryIdentifier/index.tsx
  client/src/components/productList/RecentlySearchTermBox/index.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/pages/ProductList/index.tsx
Labels: high priority, feat

#81 Feature/#79 상품 리스트 컨테이너 퍼블리싱
  client/src/components/ProductItem/ProductItem.tsx
  client/src/components/ProductItem/index.style.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
Labels: high priority, feat

#80 Feature/#75 순서 컴포넌트
  client/src/components/productList/CategoryFilter/index.style.ts
  client/src/components/productList/OrderFilter/index.style.ts
  client/src/components/productList/OrderFilter/index.tsx
  client/src/components/productList/OrderItem/index.style.ts
  client/src/components/productList/OrderItem/index.tsx
  client/src/pages/ProductList/index.style.ts
Labels: high priority, feat

#85 Feature/#76 페이스북 & 구글 Oauth로 사용자 정보 가져오는 API 구현
  server/.env.dev
  server/package.json
  server/src/api/index.ts
  server/src/api/routes/oauth/index.ts
  server/src/api/routes/oauth/oauthController.ts
  server/src/config/index.ts
  server/src/constants/error.ts
  server/src/constants/oauth.ts
  server/src/helper/oauth.ts
  server/src/service/oauth.ts
  server/yarn.lock
Labels: mid priority, feat

#83 Feature/#69 메인페이지 스타일링
  client/src/App.tsx
  client/src/assets/index.tsx
  client/src/assets/logo.svg
  client/src/assets/stain.svg
  client/src/components/main/IconButtons/index.tsx
  client/src/pages/Login/index.style.ts
  client/src/pages/Main/__snapshots__/index.spec.tsx.snap
  client/src/pages/Main/index.spec.tsx
  client/src/pages/Main/index.style.ts
  client/src/pages/Main/index.tsx
  client/src/styles/app.css
Labels: high priority, style

#84 Feature/#64 회원가입 페이지 oAuth 선택 폼 + 로직
  client/src/assets/index.tsx
  client/src/assets/signUpWithFacebook.svg
  client/src/assets/signUpWithGoogle.svg
  client/src/assets/signUpWithOwn.svg
  client/src/assets/title.svg
  client/src/components/modal/AlertModal/index.style.ts
  client/src/components/signup/HeaderTitle.tsx
  client/src/components/signup/LeftDoodles.tsx
  client/src/components/signup/RightDoodles.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/components/signup/SignUpTypes.tsx
  client/src/lib/api/types/error.ts
  client/src/lib/api/users.ts
  client/src/pages/Login/index.tsx
  client/src/pages/SignUp/__snapshots__/index.spec.tsx.snap
  client/src/pages/SignUp/index.fc.tsx
  client/src/pages/SignUp/index.style.ts
  client/src/pages/SignUp/index.tsx
  client/src/styles/app.css
Labels: mid priority, feat, style

#86 2차 출항
  README.md
  client/src/App.tsx
  client/src/assets/index.tsx
  client/src/assets/logo.svg
  client/src/assets/signUpWithFacebook.svg
  client/src/assets/signUpWithGoogle.svg
  client/src/assets/signUpWithOwn.svg
  client/src/assets/stain.svg
  client/src/assets/title.svg
  client/src/components/ProductItem/ProductItem.tsx
  client/src/components/ProductItem/index.style.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/main/IconButtons/index.tsx
  client/src/components/modal/AlertModal/index.style.ts
  client/src/components/productList/CategoryFilter/index.style.ts
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/CategoryIdentifier/index.style.ts
  client/src/components/productList/CategoryIdentifier/index.tsx
  client/src/components/productList/OrderFilter/index.style.ts
  client/src/components/productList/OrderFilter/index.tsx
  client/src/components/productList/OrderItem/index.style.ts
  client/src/components/productList/OrderItem/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/productList/RecentlySearchTermBox/index.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/signup/HeaderTitle.tsx
  client/src/components/signup/LeftDoodles.tsx
  client/src/components/signup/RightDoodles.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/components/signup/SignUpTypes.tsx
  client/src/lib/api/types/error.ts
  client/src/lib/api/users.ts
  client/src/pages/Login/index.style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Main/__snapshots__/index.spec.tsx.snap
  client/src/pages/Main/index.spec.tsx
  client/src/pages/Main/index.style.ts
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
  client/src/pages/SignUp/__snapshots__/index.spec.tsx.snap
  client/src/pages/SignUp/index.fc.tsx
  client/src/pages/SignUp/index.style.ts
  client/src/pages/SignUp/index.tsx
  client/src/styles/app.css
  scripts/after-deploy.sh
  server/.env.dev
  server/package.json
  server/src/api/index.ts
  server/src/api/routes/oauth/index.ts
  server/src/api/routes/oauth/oauthController.ts
  server/src/config/index.ts
  server/src/constants/error.ts
  server/src/constants/oauth.ts
  server/src/helper/oauth.ts
  server/src/repository/product.ts
  server/src/service/oauth.ts
  server/yarn.lock
Labels: release

#90 [#89] 회원가입 이후에 넘어온 로그인페이지에서 바로 로그인이 안되는 버그 bug
  client/src/pages/Login/index.tsx
Labels: bug

#93 Feature/#92 [FE] 자동 로그인 로직 구현
  client/src/App.tsx
  client/src/Root.tsx
  client/src/index.tsx
  client/src/lib/contexts/createNamedContext.ts
  client/src/lib/contexts/userContext.ts
  client/src/lib/hooks/useAutoLogin.ts
  client/src/lib/hooks/useInputValidator.ts
  client/src/lib/hooks/useOnClickOutside.ts
  client/src/lib/hooks/useUser.ts
  server/src/service/auth.ts
Labels: high priority, feat

#101 Bug/#100 쿠키 관련 요청 시 쿠키가 설정되지 않는 문제 해결
  client/src/lib/api/auth.ts
  client/src/lib/api/request.ts
  server/src/loaders/express.ts
  server/src/service/auth.ts
Labels: bug, high priority

#103 Feature/#88
  client/src/App.tsx
  client/src/components/cart/cart/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/cart/index.spec.tsx
  client/src/components/cart/cart/index.style.ts
  client/src/components/cart/cart/index.tsx
  client/src/components/cart/cartItem/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/cartItem/index.spec.tsx
  client/src/components/cart/cartItem/index.style.ts
  client/src/components/cart/cartItem/index.tsx
  client/src/components/cart/shipping/index.tsx
  client/src/components/main/IconButtons/index.tsx
  client/src/components/modal/ConfirmModal/index.style.ts
  client/src/components/modal/ConfirmModal/index.tsx
  client/src/lib/api/cart.ts
  client/src/lib/api/types/cart.ts
  client/src/pages/Cart/index.style.ts
  client/src/pages/Cart/index.tsx
  server/src/api/index.ts
  server/src/api/routes/cart/cartController.ts
  server/src/api/routes/cart/index.ts
  server/src/constants/error.ts
  server/src/entity/category.ts
  server/src/repository/cart.ts
  server/src/service/cart.ts
Labels: high priority, feat

#106 Bug/#105 페이지 새로고침 시 aunthorized 에러 및 이미지 업로드 에러
  client/src/components/cart/cart/index.tsx
  client/src/lib/api/types/users.ts
  client/src/lib/hooks/useUser.ts
  client/src/pages/MyPage/index.tsx
Labels: bug, high priority

#107 Feature/#102 [BE] Oauth Login API 구현
  server/.lintstagedrc.json
  server/package.json
  server/src/api/routes/oauth/index.ts
  server/src/api/routes/oauth/oauthController.ts
  server/src/constants/error.ts
  server/src/entity/login.ts
  server/src/helper/oauth.ts
  server/src/repository/login.ts
  server/src/service/oauth.ts
  server/yarn.lock
Labels: mid priority, feat

#109 Feature/#108 [FE] OAuth Callback 페이지 구현
  client/package.json
  client/src/App.tsx
  client/src/components/callback/OauthCallback.tsx
  client/src/lib/api/auth.ts
  client/src/lib/api/oauth.ts
  client/src/lib/api/types/index.ts
  client/src/lib/api/types/oauth.ts
  client/src/lib/hooks/useUser.ts
  client/src/pages/FacebookCallback/index.tsx
  client/src/pages/GoogleCallback/index.tsx
  client/src/utils/oauthStateDecoder.ts
  client/yarn.lock
Labels: mid priority, feat

#114 Feature/#113 [FE] 상품 상세 페이지 레이아웃 개발
  client/src/App.tsx
  client/src/assets/index.tsx
  client/src/components/base/Navigation/index.style.ts
  client/src/components/base/Navigation/index.tsx
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
Labels: high priority, feat

#117 Feature/#104 배송 주소지 컴포넌트
  client/package.json
  client/src/assets/cancle.svg
  client/src/assets/index.tsx
  client/src/assets/modify-pencil.svg
  client/src/assets/underline-baemin-color.svg
  client/src/assets/underline-baemin-short.svg
  client/src/components/cart/cart/index.tsx
  client/src/components/cart/cartItem/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/cartItem/index.spec.tsx
  client/src/components/cart/cartItem/index.tsx
  client/src/components/cart/shippItem/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shippItem/index.spec.tsx
  client/src/components/cart/shippItem/index.style.ts
  client/src/components/cart/shippItem/index.tsx
  client/src/components/cart/shipping/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shipping/index.spec.tsx
  client/src/components/cart/shipping/index.style.tsx
  client/src/components/cart/shipping/index.tsx
  client/src/components/cart/shippingModal/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shippingModal/index.spec.tsx
  client/src/components/cart/shippingModal/index.style.ts
  client/src/components/cart/shippingModal/index.tsx
  client/src/components/modal/ConfirmModal/index.tsx
  client/src/pages/Cart/index.tsx
  client/yarn.lock
Labels: high priority, feat

#119 Feature/#116 [BE] 상품 상세 정보 가져오는 API 구현
  server/src/api/middlewares/isAuth.ts
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/constants/error.ts
  server/src/helper/jwt.ts
  server/src/repository/cart.ts
  server/src/repository/like.ts
  server/src/repository/product.ts
  server/src/repository/productImage.ts
  server/src/repository/review.ts
  server/src/repository/user.ts
  server/src/repository/view.ts
  server/src/service/product.ts
Labels: high priority, feat

#122 Feature/#120 [BE] 조회수 API 구현
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/constants/error.ts
  server/src/repository/view.ts
  server/src/service/product.ts
Labels: low priority, feat

#121 Feature/#115 [FE] 상품 정보 퍼블리싱
  client/src/assets/index.tsx
  client/src/components/productDetail/ProductDetailContainer/index.style.tsx
  client/src/components/productDetail/ProductDetailContainer/index.tsx
  client/src/components/productDetail/SubInfos/index.style.tsx
  client/src/components/productDetail/SubInfos/index.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
  client/src/utils/fotmatPrice.ts
Labels: high priority, feat

#110 Feature/#82, #111, #112 [FE] 상품 목록 페이지 로직 구현 및 이슈 해결
  client/src/components/ProductItem/index.style.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/OrderFilter/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/productList/ScrollToTop/index.style.tsx
  client/src/components/productList/ScrollToTop/index.tsx
  client/src/components/productList/SearchBox/index.style.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/productList/SearchTerm/index.tsx
  client/src/lib/api/types/products.ts
  client/src/lib/hooks/useDebounce.ts
  client/src/lib/hooks/useIntersection.ts
  client/src/pages/ProductList/index.tsx
  client/src/stores/productListModule.ts
  client/src/styles/app.css
  client/src/utils/formatPrice.ts
  client/src/utils/localStorage.ts
  client/src/utils/modal.ts
  client/src/utils/validation.ts
Labels: high priority, feat

#128 Feature/#118 [BE] 배송정보 관련 API 구현 #118 Open
  server/.lintstagedrc.json
  server/src/api/index.ts
  server/src/api/routes/cart/cartController.ts
  server/src/api/routes/cart/index.ts
  server/src/api/routes/shipping/index.ts
  server/src/api/routes/shipping/shippingController.ts
  server/src/constants/error.ts
  server/src/entity/shipping.ts
  server/src/repository/shipping.ts
  server/src/service/cart.ts
  server/src/service/shipping.ts
Labels: high priority, feat

#131 Feature/#129 [BE] 좋아요 관련 API 구현 및 validation
  server/src/api/index.ts
  server/src/api/routes/like/index.ts
  server/src/api/routes/like/likeController.ts
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/constants/error.ts
  server/src/repository/like.ts
  server/src/service/like.ts
  server/src/service/product.ts
  server/src/service/shipping.ts
  server/src/service/users.ts
Labels: high priority, feat

#130 Feature/#126 공통 컴포넌트 개발
  client/src/components/common/LoadingText/index.style.ts
  client/src/components/common/LoadingText/index.tsx
  client/src/components/common/LoadingText/phrases.ts
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/CategoryItem/index.tsx
  client/src/components/productList/OrderFilter/index.tsx
  client/src/components/productList/OrderItem/index.tsx
  client/src/components/productList/ProductItemContainer/index.style.ts
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/productList/SearchBox/index.style.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/productList/SearchBox/useSearchTerm.ts
  client/src/components/productList/SearchTerm/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/stores/fetchModule.ts
  client/src/styles/app.css
  client/src/utils/getRandomIndex.ts
Labels: high priority, feat

#135 Feature/#135 [FE, BE] 비밀번호 정규식 개선
  client/src/utils/validation.ts
  server/src/helper/validation.ts
Labels: high priority, feat

#137 Feature/#127 [FE] 좋아요 리스트 페이지 구현
  client/.eslintrc.js
  client/.lintstagedrc.json
  client/package.json
  client/src/App.tsx
  client/src/assets/index.tsx
  client/src/components/ProductItem/index.style.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/base/Copyright/index.spec.tsx
  client/src/components/cart/cart/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/cartItem/index.spec.tsx
  client/src/components/cart/shippItem/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shippItem/index.spec.tsx
  client/src/components/cart/shippItem/index.style.ts
  client/src/components/cart/shipping/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shipping/index.style.tsx
  client/src/components/cart/shipping/index.tsx
  client/src/components/cart/shippingModal/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shippingModal/index.spec.tsx
  client/src/components/cart/shippingModal/index.tsx
  client/src/components/common/Divider/__snapshots__/index.spec.tsx.snap
  client/src/components/common/Divider/index.spec.tsx
  client/src/components/common/Divider/index.tsx
  client/src/components/common/Input/index.spec.tsx
  client/src/components/common/Space/index.tsx
  client/src/components/login/InputHelp/index.spec.tsx
  client/src/components/login/InputHelp/index.ts
  client/src/components/modal/ConfirmModal/index.tsx
  client/src/components/my/EmailInput/index.tsx
  client/src/components/product/ProductImage/index.ts
  client/src/components/product/ProductItem/__snapshots__/index.spec.tsx.snap
  client/src/components/product/ProductItem/index.spec.tsx
  client/src/components/product/ProductItem/index.style.ts
  client/src/components/product/ProductItem/index.tsx
  client/src/components/product/ProductItemWrapper/index.ts
  client/src/components/product/ProductLikeButton/index.style.ts
  client/src/components/product/ProductLikeButton/index.tsx
  client/src/components/productDetail/ProductDetailContainer/index.tsx
  client/src/components/productDetail/SubInfos/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/components/subpage/SubPageHeader/index.style.ts
  client/src/components/subpage/SubPageHeader/index.tsx
  client/src/components/subpage/SubPageHeaderItem/index.ts
  client/src/components/subpage/SubPageWrapper/index.ts
  client/src/core/Router.tsx
  client/src/pages/Cart/index.style.ts
  client/src/pages/Cart/index.tsx
  client/src/pages/LikeList/index.style.ts
  client/src/pages/LikeList/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/MyPage/__snapshots__/index.spec.tsx.snap
  client/src/pages/MyPage/index.style.ts
  client/src/pages/MyPage/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/stores/productListModule.ts
  client/yarn.lock
Labels: high priority, feat

#144 Feature/#99 메인페이지 스페샬✨ 기능
  client/.env.dev
  client/.env.prod
  client/package.json
  client/src/components/main/Minimi/cat/cat.css
  client/src/components/main/Minimi/cat/cat.txt
  client/src/components/main/Minimi/chicken/chicken.css
  client/src/components/main/Minimi/chicken/chicken.txt
  client/src/components/main/Minimi/coord.ts
  client/src/components/main/Minimi/flower/flower.css
  client/src/components/main/Minimi/flower/flower.txt
  client/src/components/main/Minimi/hedgehog/hedgehog.css
  client/src/components/main/Minimi/hedgehog/hedgehog.txt
  client/src/components/main/Minimi/hen/hen.css
  client/src/components/main/Minimi/hen/hen.txt
  client/src/components/main/Minimi/index.tsx
  client/src/components/main/Minimi/ladybug/ladybug.css
  client/src/components/main/Minimi/ladybug/ladybug.txt
  client/src/components/main/Minimi/rooster/rooster.css
  client/src/components/main/Minimi/rooster/rooster.txt
  client/src/components/main/Minimi/sonic/sonic.css
  client/src/components/main/Minimi/sonic/sonic.txt
  client/src/lib/api/peer.ts
  client/src/lib/api/socket.ts
  client/src/pages/Main/__snapshots__/index.spec.tsx.snap
  client/src/pages/Main/index.spec.tsx
  client/src/pages/Main/index.tsx
  client/src/utils/random.ts
  client/webpack.config.js
  client/yarn.lock
  server/.env.dev
  server/package.json
  server/src/bin/www.ts
  server/yarn.lock
Labels: mid priority, feat

#141 Feature/#140 [FE] 상품 상세 정보에서 장바구니 & 좋아요 API 연동 처리
  client/src/components/productDetail/ProductDetailContainer/index.style.tsx
  client/src/components/productDetail/ProductDetailContainer/index.tsx
  client/src/pages/ProductDetail/index.tsx
Labels: high priority, feat

#143 Refactor#142 [BE] 로그인 API 데이터 검증 로직 추가
  server/src/service/auth.ts
Labels: refactor, high priority

#138 Feature/#136, #139 장바구니 관련 API 개발 및 수정, 비밀번호 정규식 개선
  server/src/api/routes/cart/cartController.ts
  server/src/api/routes/cart/index.ts
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/api/routes/shipping/shippingController.ts
  server/src/constants/error.ts
  server/src/repository/cart.ts
  server/src/service/cart.ts
Labels: high priority, db, feat

#147 Feature/#132 [BE] 상품 테이블 DB 수정
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/lib/api/types/products.ts
  client/src/pages/ProductList/index.tsx
  server/src/constants/error.ts
  server/src/entity/product.ts
  server/src/repository/product.ts
  server/src/service/cart.ts
  server/src/service/like.ts
  server/src/service/product.ts
  server/src/service/shipping.ts
  server/src/service/users.ts
Labels: high priority, db

#153 Feature/#145 [FE] 헤더 컴포넌트 가장 기본 UI 구현
  client/src/components/base/HeaderLogo/index.style.ts
  client/src/components/base/HeaderLogo/index.tsx
  client/src/components/base/Navigation/index.style.ts
  client/src/components/base/Navigation/index.tsx
  client/src/components/common/ProfileImage/index.ts
  client/src/components/my/PhoneInput/index.tsx
  client/src/components/product/ProductLikeButton/index.style.ts
  client/src/lib/constants/.gitkeep
  client/src/lib/constants/urls.ts
  client/src/pages/MyPage/__snapshots__/index.spec.tsx.snap
  client/src/pages/MyPage/index.style.ts
  client/src/pages/MyPage/index.tsx
Labels: high priority, feat

#155 Feature/#150 No Resource Component 개발
  client/src/assets/index.tsx
  client/src/components/common/NoResource/index.style.ts
  client/src/components/common/NoResource/index.tsx
  client/src/components/productList/ProductItemContainer/index.style.ts
  client/src/components/productList/ProductItemContainer/index.tsx
Labels: mid priority, feat

#156 Feature/#146 [FE] API 타입 작성
  client/src/lib/api/cart.ts
  client/src/lib/api/likes.ts
  client/src/lib/api/shipping.ts
  client/src/lib/api/types/cart.ts
  client/src/lib/api/types/likes.ts
  client/src/lib/api/types/products.ts
  client/src/lib/api/types/shippings.ts
  client/src/pages/LikeList/index.tsx
  server/src/api/routes/like/index.ts
  server/src/api/routes/shipping/index.ts
  server/src/service/cart.ts
Labels: refactor, high priority, docs, feat

#159 Feature/#151 [FE] <head> 태그 관련 개발
  client/src/App.tsx
  client/src/components/productList/ProductItemContainer/index.style.ts
  client/src/index.html
  client/src/lib/constants/titles.ts
Labels: mid priority, feat

#164 4-1 출항
  README.md
Labels: release

#172 feature/#124 useDebounce 개선
  client/src/components/product/ProductItem/index.tsx
  client/src/lib/hooks/useDebounce.ts
  client/src/utils/debounce.ts
Labels: refactor, high priority

#169 Feature/#158 [FE] 헤더 컴포넌트 API 연동 및 API 타입 수정 반영
  client/src/Root.tsx
  client/src/components/base/Navigation/index.tsx
  client/src/components/cart/cart/index.tsx
  client/src/components/cart/cartItem/index.spec.tsx
  client/src/components/cart/cartItem/index.tsx
  client/src/components/productDetail/ProductDetailContainer/index.tsx
  client/src/lib/api/types/cart.ts
  client/src/lib/api/types/likes.ts
  client/src/lib/api/types/products.ts
  client/src/lib/contexts/cartAmountContext.ts
  client/src/lib/contexts/setCartAmountContext.ts
  client/src/lib/hooks/useCartAmount.ts
  client/src/lib/hooks/useSetCartAmount.ts
  client/src/pages/LikeList/index.tsx
  client/src/pages/ProductDetail/index.tsx
Labels: refactor, high priority, feat

#167 Feature/#157 [FE] 배송정보 컴포넌트 수정 및 API 연동
  client/src/components/cart/shipping/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shipping/index.tsx
  client/src/components/cart/shippingModal/__snapshots__/index.spec.tsx.snap
  client/src/components/cart/shippingModal/index.tsx
  client/src/index.html
  client/src/pages/Cart/index.tsx
  server/src/repository/shipping.ts
Labels: high priority, feat

#173 Feature/#168 [BE] 삭제 관련 API 추가
  client/src/lib/api/products.ts
  client/src/lib/api/types/products.ts
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/repository/like.ts
  server/src/service/product.ts
Labels: high priority, feat

#178 Feature/#176 [BE] 상품 정보 업로드 API 추가
  server/src/api/routes/product/index.ts
  server/src/api/routes/product/productController.ts
  server/src/constants/error.ts
  server/src/entity/product.ts
  server/src/repository/category.ts
  server/src/repository/product.ts
  server/src/repository/productImage.ts
  server/src/service/product.ts
Labels: high priority, feat

#182 Refactor/#91 [리팩토링] 초기 로딩 속도 개선을 위한 폰트 파일 및 스크립트 번들링 파일 용량 최적화
  client/package.json
  client/src/assets/fonts/BMHANNAPro.otf
  client/src/assets/fonts/BMHANNAPro.woff
  client/src/assets/fonts/BMHANNAPro.woff2
  client/src/assets/fonts/KyoboHandwriting2019.woff
  client/src/assets/fonts/KyoboHandwriting2019.woff2
  client/src/styles/font.css
  client/webpack.config.js
  client/webpack/webpack.config.common.js
  client/webpack/webpack.config.dev.js
  client/webpack/webpack.config.prod.js
  client/yarn.lock
Labels: refactor, high priority

#180 Feature/#174 [FE] 상품 추천 컴포넌트 생성
  client/src/components/productDetail/ProductDetailContainer/index.style.tsx
  client/src/components/productDetail/ProductRecommend/index.style.ts
  client/src/components/productDetail/ProductRecommend/index.tsx
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
Labels: high priority, feat

#241 Feature/#216,219 에러수정 - 헤더 개선
  client/src/assets/festival.svg
  client/src/assets/index.tsx
  client/src/components/base/Navigation/index.style.ts
  client/src/components/base/Navigation/index.tsx
  client/src/components/cart/Cart/index.tsx
  client/src/core/Router.tsx
Labels: bug, high priority, improve

#242 Refactor/#240 [FE] 회원가입 페이지 컴포넌트 분리
  client/src/components/common/PhoneInput/index.style.ts
  client/src/components/common/PhoneInput/index.tsx
  client/src/components/common/UnderLine/index.style.ts
  client/src/components/common/UnderLine/index.tsx
  client/src/components/my/MyPagePhoneInput/__snapshots__/index.spec.tsx.snap
  client/src/components/my/MyPagePhoneInput/index.spec.tsx
  client/src/components/my/MyPagePhoneInput/index.style.ts
  client/src/components/my/MyPagePhoneInput/index.tsx
  client/src/components/my/PhoneInput/__snapshots__/index.spec.tsx.snap
  client/src/components/signup/SignUpEmailInput/index.tsx
  client/src/components/signup/SignUpForm.tsx
  client/src/components/signup/SignUpForm/index.style.ts
  client/src/components/signup/SignUpForm/index.tsx
  client/src/components/signup/SignUpInput/index.style.ts
  client/src/components/signup/SignUpInput/index.tsx
  client/src/components/signup/SignUpInputWrapper/index.ts
  client/src/components/signup/SignUpLabel/index.style.ts
  client/src/components/signup/SignUpLabel/index.tsx
  client/src/components/signup/SignUpOwnForm/index.tsx
  client/src/components/signup/SignUpPhoneInput/index.style.ts
  client/src/components/signup/SignUpPhoneInput/index.tsx
  client/src/components/signup/SignUpPolicyCheck/index.style.ts
  client/src/components/signup/SignUpPolicyCheck/index.tsx
  client/src/lib/hooks/useInputValidator.ts
  client/src/pages/MyPage/index.tsx
  client/src/utils/validation.ts
Labels: bug, refactor, mid priority

#247 Feature/#206 마이페이지, 상세페이지 새로고침 시 문제점 해결
  client/src/pages/MyPage/index.tsx
  client/src/pages/ProductDetail/index.tsx
  server/src/api/routes/product/productController.ts
  server/src/service/product.ts
Labels: bug, high priority

#246 Bug/#211,212 Auth 관련 장바구니 뱃지, 페이지 이슈 해결
  client/src/components/base/Navigation/index.tsx
  client/src/pages/CartAndShipping/index.tsx
  client/src/pages/LikeList/index.tsx
Labels: mid priority, improve

#249 Refactor#248 [FE] context들 lib/contexts로 이동
  client/src/lib/contexts/fetchContext.ts
  client/src/lib/contexts/filterContext.ts
  client/src/lib/hooks/useScrollPoint.ts
  client/src/pages/ProductList/index.tsx
Labels: refactor, mid priority

#250 Bug/#224 좋아요 페이지 새로고침 시 메인으로 이동문제 해결
  client/src/components/cart/Cart/index.tsx
  client/src/components/signup/SignUpPolicyCheck/index.style.ts
  client/src/components/signup/SignUpPolicyCheck/index.tsx
  client/src/lib/constants/terms.ts
  client/src/pages/LikeList/index.tsx
Labels: bug, high priority

#252 Bug/#215,225,227 상품 목록 페이지 버그들 수정
  client/src/assets/category-all.svg
  client/src/assets/index.tsx
  client/src/components/productList/CategoryFilter/index.style.ts
  client/src/components/productList/CategoryFilter/index.tsx
  client/src/components/productList/CategoryIdentifier/index.tsx
  client/src/components/productList/CategoryItem/index.tsx
  client/src/components/productList/OrderFilter/index.tsx
  client/src/components/productList/OrderItem/index.tsx
  client/src/components/productList/ScrollToTop/index.tsx
  client/src/components/productList/SearchBox/index.style.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/lib/hooks/useSearchTerm.ts
  client/src/pages/ProductList/index.style.ts
  client/src/pages/ProductList/index.tsx
  client/src/utils/scrollToTop.ts
Labels: bug, mid priority, improve

#255 Feature/#254 페이지 전환 시 문구 보여주도록 수정
  client/package.json
  client/src/App.tsx
  client/src/Routes.tsx
  client/src/components/common/LoadingText/index.style.ts
  client/src/components/common/LoadingText/index.tsx
  client/src/components/common/LoadingText/phrases.ts
  client/src/utils/elementFade.ts
  client/src/utils/requestAnimFrame.ts
  client/yarn.lock
Labels: mid priority, feat

#259 Feature/#253 [BE] view api 적용 및 추천상품 로직 변경
  client/src/pages/ProductDetail/index.tsx
  server/src/api/routes/product/productController.ts
  server/src/repository/view.ts
  server/src/service/product.ts
Labels: high priority, feat

#262 Bug/#257,258 상품 목록 페이지 스크롤 개선
  client/src/components/productList/ProductItemContainer/index.style.ts
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/lib/contexts/filterContext.ts
  client/src/lib/hooks/useIntersection.ts
  client/src/pages/ProductList/index.tsx
  client/src/stores/fetchModule.ts
Labels: bug, high priority, mid priority, improve

#263 Bug/#222 구글 회원가입 / 로그인 오류 수정
  client/src/components/callback/OauthCallback.tsx
  client/src/components/signup/SignUpForm/index.tsx
  client/src/components/signup/SignUpPolicyCheck/index.tsx
  client/src/stores/userModule.ts
  server/src/api/routes/users/usersController.ts
  server/src/service/users.ts
Labels: bug, high priority

#265 Bug/#205,208 로그인, 회원가입 로고 이슈, 장바구니 클릭 이슈 수정
  client/src/components/base/HeaderTitle/index.tsx
  client/src/components/common/LoadingText/phrases.ts
  client/src/components/productDetail/ProductDetailContainer/index.style.tsx
  client/src/components/productDetail/SubInfos/index.style.tsx
  client/src/components/signup/SignUpForm/index.tsx
  client/src/components/signup/SignUpTypes.tsx
  client/src/core/Router.tsx
  client/src/pages/Login/index.style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
Labels: bug, mid priority, improve

#268 Bug/#260 Oauth 중복 가입 문제
  client/src/components/callback/OauthCallback.tsx
  client/src/lib/api/types/oauth.ts
  server/src/api/routes/oauth/oauthController.ts
  server/src/service/oauth.ts
Labels: bug, high priority

#272 Fix#221 스크롤 진행바 전체 비율로 설정하도록 수정
  client/src/assets/scrollProgressImage.png
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
Labels: bug, low priority

#274 [#273]fix: 새로고침 시 상품목록 페이지로 이동
  client/src/components/base/ProfileIcon/index.tsx
  client/src/pages/CartAndShipping/index.tsx
  client/src/pages/LikeList/index.tsx
  client/src/pages/MyPage/index.tsx
Labels: bug, high priority

#275 Bug/#213 아이템 리스트 => 상세페이지 후 뒤로가기했을 때 상태 저장 문제
  client/src/Root.tsx
  client/src/Routes.tsx
  client/src/components/productDetail/ProductDetailImages/index.tsx
  client/src/components/productList/CategoryItem/index.style.ts
  client/src/components/productList/CategoryItem/index.tsx
  client/src/components/productList/OrderItem/index.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/productList/SearchTerm/index.tsx
  client/src/core/Router.tsx
  client/src/lib/constants/categories.ts
  client/src/lib/contexts/filterContext.ts
  client/src/lib/hooks/useSearchTerm.ts
  client/src/pages/ProductDetail/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/stores/productFilterModule.ts
Labels: bug, low priority

#277 Feature/#165 custom-styled-components 일부 적용
  client/.babelrc
  client/package.json
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/signup/SignUpPolicyCheck/index.style.ts
  client/src/lib/customStyledComponents/constructWithTag.tsx
  client/src/lib/customStyledComponents/index.tsx
  client/src/lib/customStyledComponents/utils/applyToHead.ts
  client/src/lib/customStyledComponents/utils/checkIsValidDOMProps.ts
  client/src/lib/customStyledComponents/utils/cssParser.ts
  client/src/lib/customStyledComponents/utils/cssStringify.ts
  client/src/lib/customStyledComponents/utils/domElements.ts
  client/src/lib/customStyledComponents/utils/generateAlphaName.ts
  client/src/pages/Login/index.style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/SignUp/index.style.ts
  client/yarn.lock
Labels: high priority, feat

#279 벌써 7차 출항이라니
  README.md
  client/.babelrc
  client/package.json
  client/src/Root.tsx
  client/src/Routes.tsx
  client/src/assets/scrollProgressImage.png
  client/src/components/base/ProfileIcon/index.tsx
  client/src/components/productDetail/ProductDetailImages/index.tsx
  client/src/components/productList/CategoryItem/index.style.ts
  client/src/components/productList/CategoryItem/index.tsx
  client/src/components/productList/OrderItem/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/components/productList/SearchBox/index.tsx
  client/src/components/productList/SearchTerm/index.tsx
  client/src/components/signup/SignUpPolicyCheck/index.style.ts
  client/src/core/Router.tsx
  client/src/lib/constants/categories.ts
  client/src/lib/contexts/filterContext.ts
  client/src/lib/customStyledComponents/constructWithTag.tsx
  client/src/lib/customStyledComponents/index.tsx
  client/src/lib/customStyledComponents/utils/applyToHead.ts
  client/src/lib/customStyledComponents/utils/checkIsValidDOMProps.ts
  client/src/lib/customStyledComponents/utils/cssParser.ts
  client/src/lib/customStyledComponents/utils/cssStringify.ts
  client/src/lib/customStyledComponents/utils/domElements.ts
  client/src/lib/customStyledComponents/utils/generateAlphaName.ts
  client/src/lib/hooks/useSearchTerm.ts
  client/src/pages/CartAndShipping/index.tsx
  client/src/pages/LikeList/index.tsx
  client/src/pages/Login/index.style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/ProductDetail/index.style.ts
  client/src/pages/ProductDetail/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/pages/SignUp/index.style.ts
  client/src/stores/productFilterModule.ts
  client/src/utils/browserDetect.ts
  client/yarn.lock
  server/src/api/routes/product/index.ts
Labels: release

#281 Bug/#280 화면에 다 렌더되기 전에 observing 이 먼저 발생할 경우, 다음 페이지로 재요청
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/pages/ProductList/index.tsx
Labels: bug, high priority, improve

#283 Improve/#282 마우스 hover 시 카테고리 이름을 알려주는 tooltip 추가
  README.md
  client/package.json
  client/src/components/main/IconButtons/index.tsx
  client/src/lib/constants/categories.ts
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
Labels: low priority, improve

#285 [#284]test: UserInfoInput 컴포넌트 단위 테스트 케이스 추가
  client/src/components/my/UserInfoInput/index.spec.tsx
Labels: low priority, improve

#287 마지막 출항
  README.md
  client/package.json
  client/src/components/main/IconButtons/index.tsx
  client/src/components/main/RTCVideo/index.tsx
  client/src/components/my/UserInfoInput/index.spec.tsx
  client/src/components/productDetail/ProductDetailContainer/index.tsx
  client/src/components/productList/ProductItemContainer/index.tsx
  client/src/lib/constants/categories.ts
  client/src/lib/customStyledComponents/constructWithTag.tsx
  client/src/lib/customStyledComponents/utils/cssParser.ts
  client/src/pages/Login/index.style.ts
  client/src/pages/Main/index.tsx
  client/src/pages/ProductList/index.tsx
  client/src/utils/debounce.ts
  client/src/utils/fotmatPrice.ts
  client/webpack/webpack.config.prod.js
  server/.env.dev
Labels: release
